# Generated by Django 5.2.7 on 2025-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwJourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(help_text='Write your introduction here')),
                ('hobbies', models.TextField(help_text='List your hobbies here')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the topic', max_length=200)),
                ('challenges', models.TextField(help_text='Challenges faced while learning this topic')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMePage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
