# Generated by Django 5.2.7 on 2025-10-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwJourney', '0002_aboutme_topic_delete_aboutmepage_delete_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='challenges',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or tagline'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name',
            field=models.CharField(default='Dorji Wangmo', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='Short description about the topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which the topic appears'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='dwJourney.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='dwJourney.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=50)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='dwJourney.aboutme')),
            ],
        ),
    ]
